### ISSUE TITLE
How to pass --dns-cloudflare-credentials

### ISSUE THREAD

**Issue by RodolfoGS** [KiraLT/certbot-lambda#1]
Hi, I'm trying to implement this script, I'm using `dns-cloudflare` and I need to pass the `--dns-cloudflare-credentials`.

Do you know how I can do this?

Thanks,

**Comment by KiraLT** [comment]
I added support for more configuration options. Try adding `CERTBOT_CREDENTIALS` env variable with assigned credentials file content to it.

Example:
```bash
CERTBOT_CREDENTIALS="dns_cloudflare_api_token = 0123456789abcdef0123456789abcdef01234567"
```
